# Generated by Django 4.2.20 on 2025-04-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='response_data',
            field=models.TextField(blank=True, help_text='Raw response data from M-Pesa API', null=True),
        ),
    ]
