# Generated by Django 4.2.20 on 2025-04-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_auth', '0002_paymenttransaction_response_data'),
    ]

    operations = [
    ]
